### ISSUE TITLE
Force.com Canvas can not locate an installed canvas app with the namespace [cnvstart] and API name [Canvas_Starter_Kit].

### ISSUE THREAD

**Issue by sdbarrington** [seedcode/canvas-starter-kit#1]
Thanks for the great tutorial!

I followed along, but when I go to the tab I get this error...

Force.com Canvas can not locate an installed canvas app with the namespace [cnvstart] and API name [Canvas_Starter_Kit].

**Comment by JasonChrYoung** [comment]
Hi,
Sorry for the slow response!
I think this is a namespace issue, and cnvstart is the one we have reserved for our managed package, so you don't want to use that one. You either want to set up your own namespace for the org, or not use one at all. We recommend setting one up as you need it for the managed package.

I should add some commenting to the visualforce page to make it clear that the prefix referenced there in the canvas element is a placeholder.

Let me know if that helps.
-Jason
